In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [3]:
#read the data
df = pd.read_csv("D:\EDA model\data\insurance.csv")
df.head()
df_cleaned = df.copy()

In [4]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df_cleaned.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df_cleaned.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [7]:
df_cleaned.drop_duplicates(inplace=True)

In [8]:
df_cleaned.shape

(1337, 7)

In [9]:
# feature encoding 
df_cleaned.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [10]:
for i in ["sex" , "smoker" , "region"] :
    list = df[i].unique()
    print(f"{i} = {list}")

sex = ['female' 'male']
smoker = ['yes' 'no']
region = ['southwest' 'southeast' 'northwest' 'northeast']

In [11]:
df_cleaned["sex"] = df_cleaned["sex"].map({'female' : 1 , 'male': 0} )

In [12]:
df_cleaned["smoker"] = df_cleaned["smoker"].map({'yes' : 1 , 'no': 0} )
df_cleaned["smoker"]

0       1
1       0
2       0
3       0
4       0
       ..
1333    0
1334    0
1335    0
1336    0
1337    1
Name: smoker, Length: 1337, dtype: int64

In [13]:
df_cleaned

      age  sex     bmi  children  smoker     region      charges
0      19    1  27.900         0       1  southwest  16884.92400
1      18    0  33.770         1       0  southeast   1725.55230
2      28    0  33.000         3       0  southeast   4449.46200
3      33    0  22.705         0       0  northwest  21984.47061
4      32    0  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    0  30.970         3       0  northwest  10600.54830
1334   18    1  31.920         0       0  northeast   2205.98080
1335   18    1  36.850         0       0  southeast   1629.83350
1336   21    1  25.800         0       0  southwest   2007.94500
1337   61    1  29.070         0       1  northwest  29141.36030

[1337 rows x 7 columns]

In [14]:
df_cleaned.rename(columns={"sex" : "is_female" , "smoker" : "is_smoker"} , inplace = True)

In [15]:
#encode the region
df_cleaned = pd.get_dummies(data = df_cleaned , columns=["region"] ,  )

In [16]:

df_cleaned = df_cleaned.astype(int)
df_cleaned

,age,is_female,bmi,children,is_smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,1,27,0,1,16884,0,0,0,1
1,18,0,33,1,0,1725,0,0,1,0
2,28,0,33,3,0,4449,0,0,1,0
3,33,0,22,0,0,21984,0,1,0,0
4,32,0,28,0,0,3866,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1333,50,0,30,3,0,10600,0,1,0,0
1334,18,1,31,0,0,2205,1,0,0,0
1335,18,1,36,0,0,1629,0,0,1,0
1336,21,1,25,0,0,2007,0,0,0,1
1337,61,1,29,0,1,29141,0,1,0,0

## Featured engineering andd extraction

In [17]:
# here we make featured on the basis of BMI
df_cleaned["BMI_catagory"]= pd.cut(df_cleaned["bmi"] , bins =[ 0 ,18.5 , 24.9 ,29.9 ,float("inf")] , labels=["underweight" , "normal" , "overweight" , "obesity"])
df_cleaned["BMI_catagory"].value_counts()

BMI_catagory
obesity        706
overweight     386
normal         221
underweight     24
Name: count, dtype: int64

In [18]:
df_cleaned = pd.get_dummies(df_cleaned , columns=["BMI_catagory"] )

In [19]:
df_cleaned

,age,is_female,bmi,children,is_smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest,BMI_catagory_underweight,BMI_catagory_normal,BMI_catagory_overweight,BMI_catagory_obesity
0,19,1,27,0,1,16884,0,0,0,1,False,False,True,False
1,18,0,33,1,0,1725,0,0,1,0,False,False,False,True
2,28,0,33,3,0,4449,0,0,1,0,False,False,False,True
3,33,0,22,0,0,21984,0,1,0,0,False,True,False,False
4,32,0,28,0,0,3866,0,1,0,0,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,0,30,3,0,10600,0,1,0,0,False,False,False,True
1334,18,1,31,0,0,2205,1,0,0,0,False,False,False,True
1335,18,1,36,0,0,1629,0,0,1,0,False,False,False,True
1336,21,1,25,0,0,2007,0,0,0,1,False,False,True,False
1337,61,1,29,0,1,29141,0,1,0,0,False,False,True,False

In [20]:
df_cleaned = df_cleaned.astype(int)
df_cleaned

,age,is_female,bmi,children,is_smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest,BMI_catagory_underweight,BMI_catagory_normal,BMI_catagory_overweight,BMI_catagory_obesity
0,19,1,27,0,1,16884,0,0,0,1,0,0,1,0
1,18,0,33,1,0,1725,0,0,1,0,0,0,0,1
2,28,0,33,3,0,4449,0,0,1,0,0,0,0,1
3,33,0,22,0,0,21984,0,1,0,0,0,1,0,0
4,32,0,28,0,0,3866,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,0,30,3,0,10600,0,1,0,0,0,0,0,1
1334,18,1,31,0,0,2205,1,0,0,0,0,0,0,1
1335,18,1,36,0,0,1629,0,0,1,0,0,0,0,1
1336,21,1,25,0,0,2007,0,0,0,1,0,0,1,0
1337,61,1,29,0,1,29141,0,1,0,0,0,0,1,0

In [21]:
df_cleaned.columns

Index(['age', 'is_female', 'bmi', 'children', 'is_smoker', 'charges',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest', 'BMI_catagory_underweight', 'BMI_catagory_normal',
       'BMI_catagory_overweight', 'BMI_catagory_obesity'],
      dtype='object')

In [22]:
from sklearn.preprocessing import StandardScaler
cols = ["age","bmi","children"]
scaler = StandardScaler()

df_cleaned[cols] = scaler.fit_transform(df_cleaned[cols])

In [23]:
df_cleaned.columns

Index(['age', 'is_female', 'bmi', 'children', 'is_smoker', 'charges',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest', 'BMI_catagory_underweight', 'BMI_catagory_normal',
       'BMI_catagory_overweight', 'BMI_catagory_obesity'],
      dtype='object')

In [24]:
from scipy.stats import pearsonr
import pandas as pd

selected_feature = [
    'age', 'is_female', 'bmi', 'children', 'is_smoker',
    'region_northeast', 'region_northwest', 'region_southeast',
    'region_southwest', 'BMI_catagory_normal',
    'BMI_catagory_overweight', 'BMI_catagory_obesity'
]

correlation_data = []

for feature in selected_feature:
    
    corr, p_value = pearsonr(df_cleaned[feature], df_cleaned['charges'])
    
    correlation_data.append({
        "feature": feature,
        "correlation": corr,
        "p_value": p_value
    })

corr_df = pd.DataFrame(correlation_data)
corr_df.sort_values(by= "correlation" , ascending=False)

                    feature  correlation        p_value
4                 is_smoker     0.787234  1.409109e-282
0                       age     0.298309   6.974243e-29
11     BMI_catagory_obesity     0.200348   1.425319e-13
2                       bmi     0.196236   4.514482e-13
7          region_southeast     0.073577   7.113509e-03
3                  children     0.067390   1.371578e-02
5          region_northeast     0.005946   8.280352e-01
6          region_northwest    -0.038695   1.573341e-01
8          region_southwest    -0.043637   1.107449e-01
1                 is_female    -0.058046   3.381675e-02
9       BMI_catagory_normal    -0.104042   1.383588e-04
10  BMI_catagory_overweight    -0.120601   9.787699e-06

In [100]:
final_data = df_cleaned[["age" , "is_smoker" , "bmi" , "BMI_catagory_obesity" ,"region_southeast", "charges" ,"region_northeast" ]]
final_data

,age,is_smoker,bmi,BMI_catagory_obesity,region_southeast,charges,region_northeast
0,-1.440418,1,-0.517949,0,0,16884,0
1,-1.511647,0,0.462463,1,1,1725,0
2,-0.799350,0,0.462463,1,1,4449,0
3,-0.443201,0,-1.334960,0,0,21984,0
4,-0.514431,0,-0.354547,0,0,3866,0
...,...,...,...,...,...,...,...
1333,0.767704,0,-0.027743,1,0,10600,0
1334,-1.511647,0,0.135659,1,0,2205,1
1335,-1.511647,0,0.952670,1,1,1629,0
1336,-1.297958,0,-0.844753,0,0,2007,0
1337,1.551231,1,-0.191145,0,0,29141,0

# Model

In [ ]:
from sklearn.model_selection import train_test_split    
X = final_data.drop("charges",axis=1)
Y = final_data["charges"]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error , mean_squared_error ,r2_score


model1= LinearRegression()
model2 = DecisionTreeRegressor()

tree = model2.fit(X_train, y_train)
linear = model1.fit(X_train, y_train)

prediction1 = linear.predict(X_test)
prediction2 = tree.predict(X_test)


print("Model RUN succesfully")

Model RUN succesfully

# MODEL EVALUTION

In [102]:
# Linear Regression Evaluation
print("Linear Regression")
print("MAE:", mean_absolute_error(y_test, prediction1))
print("MSE:", mean_squared_error(y_test, prediction1))
print("R2 Score:", r2_score(y_test, prediction1))

print()

# Decision Tree Evaluation
print("Decision Tree Regressor")
print("MAE:", mean_absolute_error(y_test, prediction2))
print("MSE:", mean_squared_error(y_test, prediction2))
print("R2 Score:", r2_score(y_test, prediction2))

Linear Regression
MAE: 4279.235473627112
MSE: 35847976.64158843
R2 Score: 0.8049154311244202

Decision Tree Regressor
MAE: 2877.2786069651743
MSE: 32199880.194444444
R2 Score: 0.8247683597770785